### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by owenblacker** [JeanFred/wudele-toolforge#2]
Wudele seems to work really nicely, with a major exception — it always shows me the timeslots using the timezone of the creator of the poll, without telling me what timezone that is.

A friend in UTC+01:00 created a poll and all the options show me times for UTC+01:00. Another friend in UTC-03:00 created a poll and all the options show me times for UTC-03:00. Neither of these polls tells me what timezone is being used and I am in UTC+00:00, with my browsers and system clock set appropriately.

This is the main blocker for me using Wudele instead of proprietary equivalents like Doodle — at the moment, I am not sure Wudele is ready for use for arranging meetings where participants are distributed across different timezones.

I can see that [Framadate is in maintenance mode](https://framagit.org/framasoft/framadate/framadate/-/issues/545#note_920869); is there any intention to work on this codebase in order to address issues like this?

**Comment by JeanFred** [comment]
Thanks for the feedback!
> Wudele seems to work really nicely, with a major exception — it always shows me the timeslots using the timezone of the creator of the poll, without telling me what timezone that is.
> A friend in UTC+01:00 created a poll and all the options show me times for UTC+01:00. Another friend in UTC-03:00 created a poll and all the options show me times for UTC-03:00. Neither of these polls tells me what timezone is being used and I am in UTC+00:00, with my browsers and system clock set appropriately.
> This is the main blocker for me using Wudele instead of proprietary equivalents like Doodle — at the moment, I am not sure Wudele is ready for use for arranging meetings where participants are distributed across different timezones.

In a Framadate date poll, while the date is an actual date (using a date-picker), the Time options are free-form. As the docs say:
> For each selected day, you are free to suggest meeting times (e.g., "8h", "8:30", "8h-10h", "evening", etc.)

So not only is there no TZ conversion, there is no concept of TZ at all: the workaround here is that poll creators, if targeting a TZ-distributed audience, should be making the options clear − see for example https://wudele.toolforge.org/wz3FbBP14uiEqmjg


> I can see that [Framadate is in maintenance mode](https://framagit.org/framasoft/framadate/framadate/-/issues/545#note_920869); is there any intention to work on this codebase in order to address issues like this?

Yeah, it’s a bit sad :( I personally have no intention to start or maintain a fork of Framadate (but should there be such a fork, I would consider deploying it instead of the existing Framadate)

Does that answer your concerns @owenblacker ?

**Comment by owenblacker** [comment]
Aaaah, I see; that makes sense. It's simply a poll with labels and we're ascribing time-meaning to them, but we could just as easily put "morning" or "lunchtime" or some other not-actually-a-time datum in there — even using the columns to indicate a city preference within a date, like this: https://wudele.toolforge.org/L6JW4Lenl6K2e48b

Hmm, that's a little frustrating; requiring a poll-creator to ensure timezones are clear or requiring a poll-voter to perform timezone maths is suboptimal.

Thanks for the clarification @JeanFred; that is much clearer.

**Comment by Svetlana-T** [comment]
Hello, @JeanFred 

I am also interested in this feature. 
My users are spread internationally and I hate timezone conversions and unfortunately my time zone is not utc so I cannot force everyone to use my time zone.

Was there a better proposed solution now than the note that Framadate would need to be forked?
